package com.lavasoft;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * <b>A web service which performs GetIpAddress Lookups.</b>
 *
 * This class was generated by Apache CXF 4.0.0
 * 2023-04-17T23:23:10.566+03:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "GeoIPService",
                  wsdlLocation = "file:/C:/Devel/java_pft/soap-sample/src/main/resources/ipservice.wsdl",
                  targetNamespace = "http://lavasoft.com/")
public class GeoIPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://lavasoft.com/", "GeoIPService");
    public final static QName GeoIPServiceSoap = new QName("http://lavasoft.com/", "GeoIPServiceSoap");
    public final static QName GeoIPServiceSoap12 = new QName("http://lavasoft.com/", "GeoIPServiceSoap12");
    public final static QName GeoIPServiceHttpGet = new QName("http://lavasoft.com/", "GeoIPServiceHttpGet");
    public final static QName GeoIPServiceHttpPost = new QName("http://lavasoft.com/", "GeoIPServiceHttpPost");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Devel/java_pft/soap-sample/src/main/resources/ipservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GeoIPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Devel/java_pft/soap-sample/src/main/resources/ipservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GeoIPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GeoIPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeoIPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GeoIPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GeoIPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GeoIPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GeoIPServiceSoap
     */
    @WebEndpoint(name = "GeoIPServiceSoap")
    public GeoIPServiceSoap getGeoIPServiceSoap() {
        return super.getPort(GeoIPServiceSoap, GeoIPServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeoIPServiceSoap
     */
    @WebEndpoint(name = "GeoIPServiceSoap")
    public GeoIPServiceSoap getGeoIPServiceSoap(WebServiceFeature... features) {
        return super.getPort(GeoIPServiceSoap, GeoIPServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns GeoIPServiceSoap
     */
    @WebEndpoint(name = "GeoIPServiceSoap12")
    public GeoIPServiceSoap getGeoIPServiceSoap12() {
        return super.getPort(GeoIPServiceSoap12, GeoIPServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeoIPServiceSoap
     */
    @WebEndpoint(name = "GeoIPServiceSoap12")
    public GeoIPServiceSoap getGeoIPServiceSoap12(WebServiceFeature... features) {
        return super.getPort(GeoIPServiceSoap12, GeoIPServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns GeoIPServiceHttpGet
     */
    @WebEndpoint(name = "GeoIPServiceHttpGet")
    public GeoIPServiceHttpGet getGeoIPServiceHttpGet() {
        return super.getPort(GeoIPServiceHttpGet, GeoIPServiceHttpGet.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeoIPServiceHttpGet
     */
    @WebEndpoint(name = "GeoIPServiceHttpGet")
    public GeoIPServiceHttpGet getGeoIPServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(GeoIPServiceHttpGet, GeoIPServiceHttpGet.class, features);
    }


    /**
     *
     * @return
     *     returns GeoIPServiceHttpPost
     */
    @WebEndpoint(name = "GeoIPServiceHttpPost")
    public GeoIPServiceHttpPost getGeoIPServiceHttpPost() {
        return super.getPort(GeoIPServiceHttpPost, GeoIPServiceHttpPost.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeoIPServiceHttpPost
     */
    @WebEndpoint(name = "GeoIPServiceHttpPost")
    public GeoIPServiceHttpPost getGeoIPServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(GeoIPServiceHttpPost, GeoIPServiceHttpPost.class, features);
    }

}
