package com.lavasoft;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-04-17T23:23:10.549+03:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://lavasoft.com/", name = "GeoIPServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GeoIPServiceHttpPost {

    /**
     * <br/>Get Country Name by Country ISO2 code<br/>Paramater:Country Code &nbsp;&nbsp;<b>Type:String<b/><br/>Country code  format is ALPHA-2 (CA - for Canada)
     */
    @WebMethod(operationName = "GetCountryNameByISO2")
    @WebResult(name = "string", targetNamespace = "http://lavasoft.com/", partName = "Body")
    public java.lang.String getCountryNameByISO2(

        @WebParam(partName = "iso2Code", name = "iso2Code", targetNamespace = "")
        java.lang.String iso2Code
    );

    /**
     * <br/>Get Country and State XML String for a given ip address in x.x.x.x format<br/><br/>Parameter:GetIpAddress address &nbsp;&nbsp;&nbsp;&nbsp;<b>Type:String</b><br/><br/>Return:format in XML < GeoIP >< Country >US< /Country >< State >PA< /State >< /GeoIP > &nbsp;&nbsp;&nbsp;&nbsp;<b>Type:String</b>
     */
    @WebMethod(operationName = "GetLocation")
    @WebResult(name = "string", targetNamespace = "http://lavasoft.com/", partName = "Body")
    public java.lang.String getLocation()
;

    /**
     * <br/>Get Country and State XML String for a given ip address in x.x.x.x format<br/><br/>Parameter:GetIpAddress address &nbsp;&nbsp;&nbsp;&nbsp;<b>Type:String</b><br/><br/>Return:format in XML < GeoIP >< Country >US< /Country >< State >PA< /State >< /GeoIP > &nbsp;&nbsp;&nbsp;&nbsp;<b>Type:String</b>
     */
    @WebMethod(operationName = "GetIpLocation")
    @WebResult(name = "string", targetNamespace = "http://lavasoft.com/", partName = "Body")
    public java.lang.String getIpLocation(

        @WebParam(partName = "sIp", name = "sIp", targetNamespace = "")
        java.lang.String sIp
    );

    /**
     * <br/>Get Country ISO2 code by Country Name<br/>Paramater:Country Name &nbsp;&nbsp;<b>Type:String<b/>
     */
    @WebMethod(operationName = "GetCountryISO2ByName")
    @WebResult(name = "string", targetNamespace = "http://lavasoft.com/", partName = "Body")
    public java.lang.String getCountryISO2ByName(

        @WebParam(partName = "countryName", name = "countryName", targetNamespace = "")
        java.lang.String countryName
    );

    /**
     * <br/>Get Country and State XML String for a given ip address in x.x.x.x format<br/><br/>Parameter:GetIpAddress address &nbsp;&nbsp;&nbsp;&nbsp;<b>Type:String</b><br/><br/>Return:format in XML < GeoIP >< Country >US< /Country >< State >PA< /State >< /GeoIP > &nbsp;&nbsp;&nbsp;&nbsp;<b>Type:String</b> or <b>string empty</b> 
     */
    @WebMethod(operationName = "GetIpLocation_2_0")
    @WebResult(name = "string", targetNamespace = "http://lavasoft.com/", partName = "Body")
    public java.lang.String getIpLocation20(

        @WebParam(partName = "sIp", name = "sIp", targetNamespace = "")
        java.lang.String sIp
    );
}
